routes/web.php
<?php

use App\Http\Controllers\regist_beasiswa;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/daftar', function () {
    return view('daftar');
});

Route::resource('/regist', regist_beasiswa::class);
Route::get('/hasil', [regist_beasiswa::class, 'hasil'])->name('hasil');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/beasiswa_ittp.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class beasiswa_ittp extends Model
{
    use HasFactory;
    protected $table = 'beasiswa_ittps';
    protected $guarded = ['id'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/regist_beasiswa.php
<?php

namespace App\Http\Controllers;

use App\Models\beasiswa_ittp;
use Illuminate\Http\Request;

class regist_beasiswa extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'email' => 'required',
            'no_hp' => 'required',
            'semester' => 'required',
            'ipk' => 'required',
            'beasiswa' => 'required',
            'berkas' => 'required|max:5000|mimes:pdf,zip,jpg',
        ]);

        // Mengecek apakah email sudah terdaftar di database
        $emailExists = beasiswa_ittp::where('email', $request->email)->exists();
        if ($emailExists) {
            return redirect('daftar');
        }
        // menyimpan file ke dalam direktori server
        $file = $request->file('berkas');
        $nama_file = time() . "_" . $file->getClientOriginalName();
        $tujuan_upload = $file->store('public');
        $file->move($tujuan_upload, $nama_file);

        $data = new beasiswa_ittp();
        $data->nama = $request->nama;
        $data->email = $request->email;
        $data->no_hp = $request->no_hp;
        $data->semester = $request->semester;
        $data->ipk = $request->ipk;
        $data->beasiswa = $request->beasiswa;
        $data->berkas = $tujuan_upload . '/' . $nama_file;
        $data->save();

        return redirect('daftar');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function hasil()
    {
        $datas = beasiswa_ittp::all();

        $jbu = beasiswa_ittp::where('beasiswa', 'Jalur Beasiswa Unggul')->count();
        $bj = beasiswa_ittp::where('beasiswa', 'Beasiswa Jateng')->count();
        $jbm = beasiswa_ittp::where('beasiswa', 'Jalur Beasiswa Muda')->count();
        return view('hasil', compact('datas', 'jbu', 'bj', 'jbm'));
    }
}

resources/views/daftar.blade.php
@extends('layout/layout')

@section('title')
    Daftar
@endsection

@section('css')
    {{ asset('css/daftar.css') }}
@endsection

@section('nav')
    {{-- start nav --}}
    <nav class="navbar bg-light">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{{ asset('asset/logo/logo.png') }}" alt="Logo" width="auto" height="24"
                    class="d-inline-block align-text-top">
                Institut Teknologi Telkom Purwokerto
            </a>

            <ul class="nav nav-tabs justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Pilihan Beasiswa</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/daftar">Daftar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/hasil">Hasil</a>
                </li>
            </ul>
        </div>
    </nav>
    {{-- end nav --}}
@endsection

@section('content')
    {{-- start content --}}
    <div class="daftar pb-4">
        <div class="container">
            <div class="judul">
                <p>Daftar Beasiswa</p>
            </div>
            <div class="card">
                <h5 class="card-header text-center">Registrasi Beasiswa</h5>
                <div class="card-body">
                    <form action="{{ route('regist.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="nama" class="form-label">Masukkan Nama</label>
                            <input type="text" class="form-control" id="nama" aria-describedby="emailHelp"
                                name="nama" required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Masukkan Email</label>
                            <input type="email" class="form-control" id="email" aria-describedby="emailHelp"
                                name="email" required>
                        </div>
                        <div class="mb-3">
                            <label for="no_hp" class="form-label">Nomor HP</label>
                            <input type="number" class="form-control" id="no_hp" aria-describedby="emailHelp"
                                name="no_hp" required>
                        </div>
                        <div class="mb-3">
                            <label for="semester" class="form-label">Semester saat ini</label>
                            <select class="form-select" id="semester" onchange="updateIPK(this)" required
                                aria-label="Default select example" name="semester">
                                <option selected disabled>Pilih Semester</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="ipk" class="form-label">IPK Terakhir</label>
                            <input type="text" class="form-control" id="ipk" name="ipk" readonly>
                        </div>
                        <div class="mb-3">
                            <label for="beasiswa" class="form-label">Pilihan Beasiswa</label>
                            <select class="form-select" aria-label="Default select example" id="beasiswa" name="beasiswa"
                                disabled required>
                                <option selected disabled>Pilih Beasiswa</option>
                                <option value="Jalur Beasiswa Unggul">Jalur Beasiswa Unggul</option>
                                <option value="Beasiswa Jateng">Beasiswa Jateng</option>
                                <option value="Jalur Beasiswa Muda">Jalur Beasiswa Muda</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="berkas" class="form-label">Upload Berkas Syarat</label>
                            <input class="form-control" type="file" id="berkas" name="berkas" disabled required>
                        </div>

                        <div class="mb-3 pt-3 col text-center">
                            <button type="submit" class="btn btn-primary">Daftar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{-- end content --}}

    {{-- JS untuk membuat random angka IPK --}}
    <script>
        function updateIPK(semesterField) {
            var ipkField = document.getElementById('ipk');
            var ipkValue = Math.random() * (3.5 - 2.5) + 2.5;
            ipkField.value = ipkValue.toFixed(2);
            var beasiswaField = document.getElementById('beasiswa');
            if (ipkValue < 3.0) {
                beasiswaField.disabled = true;
                var uploadField = document.getElementById('berkas');
                uploadField.disabled = true;
            } else {
                beasiswaField.disabled = false;
                var uploadField = document.getElementById('berkas');
                uploadField.disabled = false
            }
        }

        const fileInput = document.querySelector("#berkas");
        fileInput.addEventListener("change", () => {
            const allowedFiles = [".jpg", ".jpeg", ".pdf", ".zip"];
            const fileName = fileInput.value;
            const extension = fileName.substring(fileName.lastIndexOf(".")).toLowerCase();

            if (!allowedFiles.includes(extension)) {
                alert("File yang diupload harus dalam format JPG, PDF, atau ZIP.");
                fileInput.value = "";
            } else if (fileInput.files[0].size > 5000000) { // mengecek ukuran file, 5000000 bytes = 5 MB
                alert("Ukuran file yang diupload tidak boleh lebih dari 5 MB.");
                fileInput.value = "";
            }
        });
    </script>
    {{-- JS untuk membuat random angka IPK --}}
@endsection

resources/views/hasil.blade.php
@extends('layout/layout')

@section('title')
    Hasil
@endsection

@section('css')
    {{ asset('css/hasil.css') }}
@endsection

@section('nav')
    {{-- start nav --}}
    <nav class="navbar bg-light">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{{ asset('asset/logo/logo.png') }}" alt="Logo" width="auto" height="24"
                    class="d-inline-block align-text-top">
                Institut Teknologi Telkom Purwokerto
            </a>

            <ul class="nav nav-tabs justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Pilihan Beasiswa</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/daftar">Daftar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/hasil">Hasil</a>
                </li>
            </ul>
        </div>
    </nav>
    {{-- end nav --}}
@endsection

@section('content')
    {{-- start content --}}
    <div class="judul">
        <p>Rekap Registrasi Beasiswa</p>
    </div>

    <div class="tabel table-responsive mb-4 container">
        <table class="table table-hover table-light rounded-3 overflow-hidden" id="tbl_user">
            <thead class="table-warning">
                <tr>
                    <th scope="col" class="text-center">No</th>
                    <th scope="col" class="text-center">Nama</th>
                    <th scope="col" class="text-center">Email</th>
                    <th scope="col" class="text-center">Nomor HP</th>
                    <th scope="col" class="text-center">IPK Terakhir</th>
                    <th scope="col" class="text-center">Pilihan Beasiswa</th>
                    <th scope="col" class="text-center">Status Ajuan</th>
                    <th scope="col" class="text-center">Lihat Berkas</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($datas as $data)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $data->nama }}</td>
                        <td>{{ $data->email }}</td>
                        <td>{{ $data->no_hp }}</td>
                        <td>{{ $data->ipk }}</td>
                        <td>{{ $data->beasiswa }}</td>
                        <td>
                            <div class="status">
                                @if ($data->status_ajuan == 'Proses')
                                    <button type="button" class="btn btn-outline-warning btn-sm" disabled>Pending</button>
                                @elseif($data->status_ajuan == 'Diterima')
                                    <button type="button" class="btn btn-outline-success btn-sm" disabled>Diterima</button>
                                @elseif($data->status_ajuan == 'Ditolak')
                                    <button type="button" class="btn btn-outline-danger btn-sm" disabled>Ditolak</button>
                                @endif
                            </div>
                        </td>
                        <td>
                            <a class="btn btn-primary btn-sm" href="{{ url($data->berkas) }}" role="button" target="_blank">Lihat Berkas</a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <input type="hidden" name="jbu" value="{{ $jbu }}" id="jbu">
    <input type="hidden" name="bj" value="{{ $bj }}" id="bj">
    <input type="hidden" name="jbm" value="{{ $jbm }}" id="jbm">

    <div class="grafik pb-4">
        <div class="judul">
            <p>Rekap Registrasi Beasiswa</p>
        </div>
        <div class="programming-stats">
            <div class="chart-container">
                <canvas class="my-chart"></canvas>
            </div>

            <div class="details">
                <ul></ul>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script src="{{ asset('js/main.js') }}"></script>
    </div>
    {{-- end content --}}
@endsection

resources/views/layout/layout.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="@yield('css')">
</head>

<body>
    <!-- start navbar -->
    @yield('nav')
    <!-- end navbar -->

    <!-- start content -->
    @yield('content')
    <!-- end content -->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>

</html>